---
title: "Dry Matter"
author: "Kolby Grint"
date: "2022-09-12"
output: pdf_document
---

```{r, echo = FALSE}
#Loading Packages
library(car)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(mgcv)
library(magrittr)
library(lmerTest)
library(lme4)
library(emmeans)
library(rstatix)
library(ggpubr)
library(multcomp)

library(nlraa)
library(minpack.lm)
library(nlstools)
library(modelr)
library(devtools)
#source("eonr.R")
```


```{r}
#Accessing CSV Data
getwd()
data1= read.csv(file="2022Data.csv")

data1 = data1 %>%
  mutate(rep= as.factor(rep),
         N_trt = as.factor(N_trt))

str(data1)
```

```{r}
data2 = data1 %>%
  group_by(N_trt, county) %>%
  summarise(DM_avg = mean(DM_total))

ggplot(data2, aes(x=N_trt, y= DM_avg)) +
  geom_point(data= data1, mapping = aes(y = DM_total, alpha = 0.01)) +
  geom_point(color= "red") + #red dots are just means
  facet_wrap(vars(county)) +
  theme(legend.position = "none")
```


# Dunn County
```{r}
data_Dunn <- data1 %>%
  filter(county == "Dunn") %>%
  slice(-c(10)) 
```

```{r, echo= FALSE}
#Testing for normality
data_Dunn %>%
  shapiro_test(DM_total)

ggqqplot(data_Dunn, "DM_total")
#looks good
```

```{r}
Dunn_mod = lmer(DM_total ~ N_trt + (1|rep), data = data_Dunn)

Dunn_AOV = anova(Dunn_mod)
#not significant, but close 

Dunn_AOV = Dunn_AOV %>%
  mutate(Location = "Dunn")
```

```{r}
Dunn_means = emmeans(Dunn_mod, ~ N_trt, contr= "pairwise", adjust= "tukey")

Dunn_CLD = cld(Dunn_means$emmean, alpha=0.05, Letters=letters, sort=FALSE, reverse=TRUE)

Dunn_CLD = as_tibble(Dunn_CLD) %>% 
  rename(DM = emmean) %>%
  mutate(DM = round(DM,2),
         Location = "Dunn")
```


# Dane
```{r}
data_Dane <- data1 %>%
  filter(county == "Dane") 
```

```{r, echo= FALSE}
#Testing for normality
data_Dane %>%
  shapiro_test(DM_total)

ggqqplot(data_Dane, "DM_total")
#looks good
```

```{r}
Dane_mod = lmer(DM_total ~ N_trt + (1|rep), data = data_Dane)

Dane_AOV = anova(Dane_mod)
#not significant

Dane_AOV = Dane_AOV %>%
  mutate(Location = "Dane")
```

```{r}
Dane_means = emmeans(Dane_mod, ~ N_trt, contr= "pairwise", adjust= "tukey")

Dane_CLD = cld(Dane_means$emmean, alpha=0.05, Letters=letters, sort=FALSE, reverse=TRUE)

Dane_CLD = as_tibble(Dane_CLD) %>% 
  rename(DM = emmean) %>%
  mutate(DM = round(DM,2),
         Location = "Dane")
```


#Door
```{r}
data_Door <- data1 %>%
  filter(county == "Door")
```

```{r, echo= FALSE}
#Testing for normality
data_Door %>%
  shapiro_test(DM_total)

ggqqplot(data_Door, "DM_total")
#looks good
```

```{r}
Door_mod = lmer(DM_total ~ N_trt + (1|rep), data = data_Door)

Door_AOV = anova(Door_mod)
#not significant

Door_AOV = Door_AOV %>%
  mutate(Location = "Door")
```

```{r}
Door_means = emmeans(Door_mod, ~ N_trt, contr= "pairwise", adjust= "tukey")

Door_CLD = cld(Door_means$emmean, alpha=0.05, Letters=letters, sort=FALSE, reverse=TRUE)

Door_CLD = as_tibble(Door_CLD) %>% 
  rename(DM = emmean) %>%
  mutate(DM = round(DM,2),
         Location = "Door")
```

# Oconto
```{r}
data_Ocon <- data1 %>%
  filter(county == "Oconto") 
```

```{r, echo= FALSE}
#Testing for normality
data_Ocon %>%
  shapiro_test(DM_total)

ggqqplot(data_Ocon, "DM_total")
#edges look bad
```

```{r}
Ocon_mod = lmer(DM_total ~ N_trt + (1|rep), data = data_Ocon)

Ocon_AOV = anova(Ocon_mod)
#significant

Ocon_AOV = Ocon_AOV %>%
  mutate(Location = "Oconto")
```

```{r}
Ocon_means = emmeans(Ocon_mod, ~ N_trt, contr= "pairwise", adjust= "tukey")

Ocon_CLD = cld(Ocon_means$emmean, alpha=0.05, Letters=letters, sort=FALSE, reverse=TRUE)

Ocon_CLD = as_tibble(Ocon_CLD) %>% 
  rename(DM = emmean) %>%
  mutate(DM = round(DM,2),
         Location = "Oconto")
```


# Marathon
```{r}
data_Mara <- data1 %>%
  filter(county == "Marathon")
```

```{r, echo= FALSE}
#Testing for normality
data_Mara %>%
  shapiro_test(DM_total)

ggqqplot(data_Mara, "DM_total")
#looks good
```

```{r}
Mara_mod = lmer(DM_total ~ N_trt + (1|rep), data = data_Mara)

Mara_AOV = anova(Mara_mod)
#not significant

Mara_AOV = Mara_AOV %>%
  mutate(Location = "Marathon")
```

```{r}
Mara_means = emmeans(Mara_mod, ~ N_trt, contr= "pairwise", adjust= "tukey")

Mara_CLD = cld(Mara_means$emmean, alpha=0.05, Letters=letters, sort=FALSE, reverse=TRUE)

Mara_CLD = as_tibble(Mara_CLD) %>% 
  rename(DM = emmean) %>%
  mutate(DM = round(DM,2),
         Location = "Marathon")
```

# Outagamie 1
```{r}
data_Outa1 <- data1 %>%
  filter(county == "Outagamie 1")
```

```{r, echo= FALSE}
#Testing for normality
data_Outa1 %>%
  shapiro_test(DM_total)

ggqqplot(data_Outa1, "DM_total")
#looks good
```

```{r}
Outa1_mod = lmer(DM_total ~ N_trt + (1|rep), data = data_Outa1)

Outa1_AOV = anova(Outa1_mod)
#not significant

Outa1_AOV = Outa1_AOV %>%
  mutate(Location = "Outagamie 1")
```

```{r}
Outa1_means = emmeans(Outa1_mod, ~ N_trt, contr= "pairwise", adjust= "tukey")

Outa1_CLD = cld(Outa1_means$emmean, alpha= 0.05, Letters=letters, sort=FALSE, reverse=TRUE)

Outa1_CLD = as_tibble(Outa1_CLD) %>% 
  rename(DM = emmean) %>%
  mutate(DM = round(DM,2),
         Location = "Outagamie 1")
```

# Outagamie 2
```{r}
data_Outa2 <- data1 %>%
  filter(county == "Outagamie 2")
```

```{r, echo= FALSE}
#Testing for normality
data_Outa2 %>%
  shapiro_test(DM_total)

ggqqplot(data_Outa2, "DM_total")
#looks good
```

```{r}
Outa2_mod = lmer(DM_total ~ N_trt + (1|rep), data = data_Outa2)

Outa2_AOV = anova(Outa2_mod)
#significant

Outa2_AOV = Outa2_AOV %>%
  mutate(Location = "Outagamie 2")
```

```{r}
Outa2_means = emmeans(Outa2_mod, ~ N_trt, contr= "pairwise", adjust= "tukey")

Outa2_CLD = cld(Outa2_means$emmean, alpha = 0.05, Letters = letters, sort = FALSE, reverse = TRUE)

Outa2_CLD = as_tibble(Outa2_CLD) %>% 
  rename(DM = emmean) %>%
  mutate(DM = round(DM,2),
         Location = "Outagamie 2")
```


```{r}
DMAnova_Results = rbind(Dunn_AOV, Dane_AOV, Door_AOV, Mara_AOV, Ocon_AOV, Outa1_AOV, Outa2_AOV)

DMMeans_Results = rbind(Dunn_CLD, Dane_CLD, Door_CLD, Mara_CLD, Ocon_CLD, Outa1_CLD, Outa2_CLD)
```

```{r}
library(writexl)
write_xlsx(DMAnova_Results, "DMAnova_Results.xlsx")
write_xlsx(DMMeans_Results, "DMMeans_Results.xlsx")
```


```{r, fig.height = 8, fig.width = 11}
DM_figure =
  DMMeans_Results %>%
  ggplot(aes(x= N_trt, y= DM)) +
  geom_point(aes(), size = 5) +
  geom_point(data= data1, aes(x= N_trt, y= DM_total), color = "red") +
  geom_pointrange(aes(ymin = lower.CL, ymax = upper.CL)) +
  geom_text(aes(label = .group), nudge_x =  0.26, size = 10) +
  facet_grid(cols = vars(Location)) +
  labs(title = "forage dry matter", x = "Nitrogen Rate", y = "dry matter (tons/acre)") +
  theme(legend.position = "none",
        axis.title.x = element_text(size = 50),
        axis.title.y = element_text(size = 50),
        axis.text.y = element_text(size = 30),
        axis.text.x = element_text(size = 30, angle = 45, hjust = 1),
        strip.text.x = element_text(size = 30),
        strip.text.y = element_text(size = 30),
        title = element_text(size = 50))

DM_figure
```

